//
// Generated file, do not edit! Created by nedtool 5.5 from file.msg.
//

#ifndef __FILE_M_H
#define __FILE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>file.msg:17</tt> by nedtool.
 * <pre>
 * message FileRequest
 * {
 *     int sourceAddress;
 *     int destAddress;
 *     string fileName;
 *     double txRate;
 *     int fileSize;
 * }
 * </pre>
 */
class FileRequest : public ::omnetpp::cMessage
{
  protected:
    int sourceAddress;
    int destAddress;
    ::omnetpp::opp_string fileName;
    double txRate;
    int fileSize;

  private:
    void copy(const FileRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FileRequest&);

  public:
    FileRequest(const char *name=nullptr, short kind=0);
    FileRequest(const FileRequest& other);
    virtual ~FileRequest();
    FileRequest& operator=(const FileRequest& other);
    virtual FileRequest *dup() const override {return new FileRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSourceAddress() const;
    virtual void setSourceAddress(int sourceAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual const char * getFileName() const;
    virtual void setFileName(const char * fileName);
    virtual double getTxRate() const;
    virtual void setTxRate(double txRate);
    virtual int getFileSize() const;
    virtual void setFileSize(int fileSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FileRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FileRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FILE_M_H

