//
// Generated file, do not edit! Created by nedtool 5.5 from file.msg.
//

#ifndef __FILE_M_H
#define __FILE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>file.msg:17</tt> by nedtool.
 * <pre>
 * packet FooPacket
 * {
 *     int sourceAddress;
 *     int destAddress;
 *     bool hasPayload;
 * }
 * </pre>
 */
class FooPacket : public ::omnetpp::cPacket
{
  protected:
    int sourceAddress;
    int destAddress;
    bool hasPayload;

  private:
    void copy(const FooPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FooPacket&);

  public:
    FooPacket(const char *name=nullptr, short kind=0);
    FooPacket(const FooPacket& other);
    virtual ~FooPacket();
    FooPacket& operator=(const FooPacket& other);
    virtual FooPacket *dup() const override {return new FooPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSourceAddress() const;
    virtual void setSourceAddress(int sourceAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual bool getHasPayload() const;
    virtual void setHasPayload(bool hasPayload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FooPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FooPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FILE_M_H

