//
// Generated file, do not edit! Created by nedtool 5.5 from file_packet.msg.
//

#ifndef __FILE_PACKET_M_H
#define __FILE_PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>file_packet.msg:17</tt> by nedtool.
 * <pre>
 * packet FilePacket
 * {
 *     int seqNumber;
 *     string fileName;
 *     int size;
 * }
 * </pre>
 */
class FilePacket : public ::omnetpp::cPacket
{
  protected:
    int seqNumber;
    ::omnetpp::opp_string fileName;
    int size;

  private:
    void copy(const FilePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FilePacket&);

  public:
    FilePacket(const char *name=nullptr, short kind=0);
    FilePacket(const FilePacket& other);
    virtual ~FilePacket();
    FilePacket& operator=(const FilePacket& other);
    virtual FilePacket *dup() const override {return new FilePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeqNumber() const;
    virtual void setSeqNumber(int seqNumber);
    virtual const char * getFileName() const;
    virtual void setFileName(const char * fileName);
    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FilePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FilePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FILE_PACKET_M_H

